apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: crda-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_DATABASE
          value: "base_objection"
        - name: MYSQL_USER
          value: "objc_user"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: app-password
        - name: MYSQL_ARGS
          value: "--default-authentication-plugin=mysql_native_password"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        - name: custom-config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
        livenessProbe:
          exec:
            command: ["mysqladmin","ping","-u${MYSQL_USER}","-p${MYSQL_PASSWORD}"]
          initialDelaySeconds: 45
          periodSeconds: 15
        readinessProbe:
          exec:
            command: ["mysqladmin","ping","-uroot","-p${MYSQL_ROOT_PASSWORD}"]
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: mysql-pvc
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: init-script
        configMap:
          name: mysql-init-script
      - name: custom-config
        configMap:
          name: mysql-config
