apiVersion: apps/v1
kind: Deployment
metadata:
  name: objection-app
  namespace: crda-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: objection-app
  template:
    metadata:
      labels:
        app: objection-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: objection-app
        image: najwa22/objection-app:{{ BUILD_TAG }}
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          value: "crda_user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: app-password
        - name: DB_NAME
          value: "base_objection"
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: session-secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: jwt-secret
        - name: NODE_ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 2
