apiVersion: apps/v1
kind: Deployment
metadata:
  name: objection-app
  namespace: crda-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: objection-app
  template:
    metadata:
      labels:
        app: objection-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: objection-app
        image: najwa22/objection-app:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_USER
          value: "objc_user"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: app-password
        - name: MYSQL_DB
          value: "base_objection"
          
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          value: "objc_user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: app-password
        - name: DB_NAME
          value: "base_objection"

        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: session-secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: jwt-secret
        - name: NODE_ENV
          value: "production"
        - name: ADMIN_USERNAME
          value: "admin"
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: admin-password
        readinessProbe:
          httpGet:
            path: /health-pod
            port: 3001 # Corrected to 3001
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 10
        livenessProbe: # Added liveness probe
          httpGet:
            path: /livez
            port: 3001 # Match the app port
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
