apiVersion: v1
kind: Service
metadata:
  name: objection-app-service
  namespace: crda-namespace
spec:
  selector:
    app: objection-app
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
